I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 269, in script
    $ count += 1
  File "game/script.rpy", line 269, in <module>
    $ count += 1
NameError: name 'count' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 269, in script
    $ count += 1
  File "C:\Users\хуй\Desktop\Новая папка\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\хуй\Desktop\Новая папка\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 269, in <module>
    $ count += 1
NameError: name 'count' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
in search of a soul 1.0
Fri Jan 19 17:21:56 2024
